42.API Delet Obat
aldhisttd/2023_5sore_apotek_be pull request #2
Opened 2023-12-10 04:41 UTC by zaky2155201002

![Untitled](https://github.com/aldhisttd/5sore_apotek_be/assets/57738588/27c4ca76-ba0e-4e3d-950a-7136441ca7d2)

2023-12-10 04:44 UTC, aldhi88 requested changes
@zaky2155201002 , baca API Spec

2023-12-10 06:01 UTC, aldhi88 requested changes
@zaky2155201002 , kirim screenshoot hasil response nya

2023-12-10 09:12 UTC, aldhi88 requested changes
@zaky2155201002 tidak sesuai API Spec

2023-12-10 09:41 UTC, zaky2155201002 commented
@aldhi88 maksud ny kek mana tu pak biar saya plajari pak

2023-12-10 11:32 UTC, aldhi88 requested changes

2023-12-10 11:32 UTC, aldhi88 commented on hapus_obat.php
> +    }
@zaky2155201002 tambahkan else nya jika gagal

2023-12-18 00:41 UTC, aldhi88 approved these changes

2023-12-18 00:41 UTC, aldhi88 commented on hapus_obat.php
> +    }else {
@zaky2155201002 , klo gini response gagal nya pasti gak sesuai API Spec....tolong sebelum PR itu di test dulu apakah semua udah sesuai dengan API spec ato belum, lampirkan Screenshoot nya...jgn main PR aja tanpa di tes, capek saya cek nya berulang2

2023-12-18 00:41 UTC, merged